### PR TITLE
Transactions from the future are not included in blocks

### PR DESCRIPTION
**Pull request by asolovyov**

### CODE REVIEW

**Comment by Tolsi** [comment]
Is this relevant?

**Comment by asolovyov** [comment]
Please check with Sasha - initially it was his req. And apart from this, another reason to add such a restriction is the current implementation of tx uniqueness check - if you accept a tx from a far future you will have to wait that moment to send next tx.

**Comment by Tolsi** [comment]
@sasha35625 @catena2w

**Comment by bcdev-** [comment]
"wait that moment" - but that applies only to SimplePayment transactions, and these are deprecated.

**Comment by Tolsi** [comment]
see wavesplatform/Scorex#179

**Pull request closed without merging**
