### PR TITLE
SC-543 Store complexity by version

### PR DESCRIPTION
**Pull request by xrtm000**

### CODE REVIEW

**Comment by lazaridiscom** [comment]
> `SC-543`

What's this?

**Comment by xrtm000** [comment]
> > `SC-543`
> 
> What's this?
Hie, @lazaridiscom!
It is task identifier

**Comment by lazaridiscom** [comment]
> 
> 
> > > `SC-543`
> > 
> > 
> > What's this?
> 
> Hie, @lazaridiscom!
> It is task identifier

But from which system? Is this an internal tracker?

**Comment by xrtm000** [comment]
@lazaridiscom, yes, it is. 
Thank you, we will follow your suggestions.

**Pull request merged**
