### PR TITLE
SC-216 ride-utf8-bytes-support

### PR DESCRIPTION
**Pull request by potan**

### CODE REVIEW

**Review by ismagin — COMMENTED** [review]
how is it better than `fromUtf8String("abc")` ?

**Comment by potan** [comment]
> how is it better than `fromUtf8String("abc")` ?
It works compile-time.

**Review by widyhafiz03 — COMMENTED** [review]
Property valid

**Comment by widyhafiz03** [comment]
https://github.com/wavesplatform/Waves/commit .. Smile

**Review by widyhafiz03 — APPROVED** [review]

**Comment by mrkraft** [comment]
Оutdated

**Pull request closed without merging**
